# Generated by Django 3.1.6 on 2021-05-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210508_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(default='Landscape Architecture', max_length=255),
        ),
    ]
