# Generated by Django 3.1.6 on 2021-05-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210508_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
